// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwimRoomWeb.Models;

#nullable disable

namespace SwimRoomWeb.Migrations
{
    [DbContext(typeof(AplicacionDbContext))]
    [Migration("20251208034808_AddCedulaToVentas")]
    partial class AddCedulaToVentas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SwimRoomWeb.Models.VentaDiferida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .HasColumnType("longtext");

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DiasAtrasoMax")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("IngresoMensual")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MontoCompra")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NivelRiesgo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumCuotas")
                        .HasColumnType("int");

                    b.Property<double>("PorcentajeCuotasPagadas")
                        .HasColumnType("double");

                    b.Property<double>("ProbabilidadMora")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("VentasDiferidas");
                });
#pragma warning restore 612, 618
        }
    }
}
